-- Generated from DM-1022 Appian MariaDB Replication.xlsx, Column Metadata.
-- The workbook does not declare foreign-key constraints; tables are created independently.
CREATE TABLE IF NOT EXISTS `MCI_BUYER_CODE` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `BUYER_CODE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`BUYER_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_COC` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `COC_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `COUNTRY_ID` INT NOT NULL,
  `IS_TD` TINYINT(1) NOT NULL DEFAULT 0,
  `PURCHASE_LL4_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL3_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL3_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL2_5_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL2_5_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL2_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `PURCHASE_LL2_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `CEO_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `CEO_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FBPA_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FBP_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FINANCE_LL4_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FINANCE_LL5_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FINANCE_LL3_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `FINANCE_LL3_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `CFO_SECRETARY_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  `CFO_APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`COC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_COC_USER_MAPPING` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `COC_USER_MAPPING_ID` INT NOT NULL,
  `COC_ID` INT NOT NULL,
  `BUYER_CODE_ID` INT NOT NULL,
  `PM_CODE_ID` INT NOT NULL,
  `SPM_CODE_ID` INT NOT NULL,
  PRIMARY KEY (`COC_USER_MAPPING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_KSB` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `KSB_ID` INT NOT NULL,
  `PROCESSING_ID` INT NOT NULL,
  `KSB_FILE_NAME` VARCHAR(255) NOT NULL,
  `COST_CENTER` VARCHAR(255) NOT NULL,
  `COST_ELEMENT` VARCHAR(255) NOT NULL,
  `TRANSACTION_CURRENCY` VARCHAR(255) NOT NULL,
  `REF_DOCUMENT_NUMBER` VARCHAR(255) NOT NULL,
  `PURCHASING_DOCUMENT` VARCHAR(255) NOT NULL,
  `DOCUMENT_TYPE` VARCHAR(255) NOT NULL,
  `VAR_VAL_IN_REP_CUR` DECIMAL(19,5) NOT NULL,
  `VALUE_TRANCURR` DECIMAL(19,5) NOT NULL,
  `POSTING_DATE` VARCHAR(255) NOT NULL,
  `DOCUMENT_NUMBER` VARCHAR(255) NOT NULL,
  `DOCUMENT_HEADER_TEXT` VARCHAR(255) NOT NULL,
  `IS_MATCHED` TINYINT(1) NOT NULL,
  PRIMARY KEY (`KSB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_PM_CODE` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `PM_CODE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `APPIAN_USER_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PM_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_AGEING` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `AGEING_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  PRIMARY KEY (`AGEING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_BASE_POSITION` (
  `BASE_POSITION_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`BASE_POSITION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_COMMODITY_LEAD_AREA` (
  `COMMODITY_LEAD_AREA_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`COMMODITY_LEAD_AREA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_CURRENCY` (
  `CURRENCY_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `CURRENCY_CODE` VARCHAR(10) NOT NULL,
  `IS_SAP_SPECIAL_CURRENCY` TINYINT(1) NOT NULL DEFAULT 0,
  `SAP_CONVERSION_FACTOR` DECIMAL(19,5) NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`CURRENCY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_ENERGY_MATERIAL_TYPE` (
  `ENERGY_MATERIAL_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `INFLATION_TYPE_ID` INT NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ENERGY_MATERIAL_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_FINANCE_STATUS` (
  `FINANCE_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`FINANCE_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_FISCAL_YEAR` (
  `FISCAL_YEAR_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`FISCAL_YEAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_INFLATION_TYPE` (
  `INFLATION_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`INFLATION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_LEVER` (
  `LEVER_ID` INT NOT NULL,
  `SHORT_CODE` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SUPER_LEVEL` VARCHAR(50) NOT NULL,
  `HIGH_LEVEL` VARCHAR(50) NOT NULL,
  `MID_LEVEL` VARCHAR(50) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`LEVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_NON_STANDARD_ACCOUNTING` (
  `NON_STANDARD_ACCOUNTING_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `IS_SYSTEM` TINYINT(1) NOT NULL DEFAULT 0,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`NON_STANDARD_ACCOUNTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PART` (
  `PART_ID` INT NOT NULL,
  `VENDOR_ID` INT NOT NULL,
  `MATERIAL` VARCHAR(255) NOT NULL,
  `PREFIX` VARCHAR(50) NOT NULL,
  `BASE` VARCHAR(50) NOT NULL,
  `SUFFIX` VARCHAR(50) NOT NULL,
  `PART_NUMBER` VARCHAR(255) NOT NULL,
  `PART_DESCRIPTION` VARCHAR(255) NOT NULL,
  `WHITE_COLOURED_PREFIX` VARCHAR(50) NOT NULL,
  `WHITE_COLOURED_BASE` VARCHAR(50) NOT NULL,
  `WHITE_COLOURED_SUFFIX` VARCHAR(50) NOT NULL,
  `WHITE_COLOURED_PART_NUMBER` VARCHAR(255) NOT NULL,
  `COLOURED_PART_INDICATOR` TINYINT(1) NOT NULL,
  `MRP_VIEW_MAINTAINED` TINYINT(1) NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`PART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PLANT` (
  `PLANT_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SAP_POA_PLANT_CODE` VARCHAR(20) NOT NULL,
  `SAP_LUMP_SUM_PLANT_CODE` VARCHAR(20) NOT NULL,
  `WIPS_PLANT_CODE` VARCHAR(20) NOT NULL,
  `WERS_PLANT_CODE` VARCHAR(20) NOT NULL,
  `MPL_CODE` VARCHAR(20) NOT NULL,
  `IS_S4_APPLIED` TINYINT(1) NOT NULL DEFAULT 0,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`PLANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_FINANCE_STATUS` (
  `RESERVE_FINANCE_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `IS_MEMO_APPLICABLE` TINYINT(1) NOT NULL DEFAULT 0,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_FINANCE_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_RISK_OPPORTUNITY_MEMO_STATUS` (
  `RESERVE_RISK_OPPORTUNITY_MEMO_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_RISK_OPPORTUNITY_MEMO_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_RISK_OPPORTUNITY_STATUS` (
  `RESERVE_RISK_OPPORTUNITY_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_RISK_OPPORTUNITY_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_STATUS` (
  `RESERVE_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_STOP_TYPE` (
  `RESERVE_STOP_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_STOP_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RESERVE_VALUE` (
  `RESERVE_VALUE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RESERVE_VALUE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_SUPPLIER_CLAIM_TYPE` (
  `SUPPLIER_CLAIM_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`SUPPLIER_CLAIM_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_SYSTEM` (
  `SYSTEM_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`SYSTEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TEAM` (
  `TEAM_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TEAM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TRANSACTION_TYPE` (
  `TRANSACTION_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TRANSACTION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TRANSACTION_TYPE_BREAKDOWN` (
  `TRANSACTION_TYPE_BREAKDOWN_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TRANSACTION_TYPE_BREAKDOWN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_UNIT_MEASURE` (
  `UNIT_MEASURE_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `INFLATION_TYPE_ID` INT NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`UNIT_MEASURE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_VENDOR` (
  `VENDOR_ID` INT NOT NULL,
  `VENDOR_CODE` VARCHAR(50) NOT NULL,
  `VENDOR_NAME` VARCHAR(50) NOT NULL,
  `PARENT_CODE` VARCHAR(50) NOT NULL,
  `PARENT_NAME` VARCHAR(50) NOT NULL,
  `CURRENCY_ID` INT NOT NULL,
  `DELETION_FLAG` TINYINT(1) NOT NULL DEFAULT 0,
  `PURCHASING_BLOCK` TINYINT(1) NOT NULL DEFAULT 0,
  `POSTING_BLOCK` TINYINT(1) NOT NULL DEFAULT 0,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`VENDOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_WORKFLOW_FINANCE_STATUS` (
  `WORKFLOW_FINANCE_STATUS_ID` INT NOT NULL,
  `PHASE_ID` INT NOT NULL,
  `WORKFLOW_STATUS_ID` INT NOT NULL,
  `FINANCE_STATUS_ID` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`WORKFLOW_FINANCE_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_WORKFLOW_STATUS` (
  `WORKFLOW_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `SORT_ORDER` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`WORKFLOW_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE` (
  `RESERVE_ID` INT NOT NULL,
  `MONTH` INT NOT NULL,
  `FISCAL_YEAR_ID` INT NOT NULL,
  `RESERVE_STATUS_ID` INT NOT NULL,
  `IS_MEMO_LOCKED` TINYINT(1) NOT NULL,
  `MEMO_LOCK_DATETIME` DATETIME NOT NULL,
  `IS_CALCULATIONS_COMPLETE` TINYINT(1) NOT NULL DEFAULT 0,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RESERVE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY` (
  `RESERVE_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `RESERVE_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `RESERVE_RISK_OPPORTUNITY_STATUS_ID` INT NOT NULL,
  `RESERVE_FINANCE_STATUS_ID` INT NOT NULL,
  `AGEING_ID` INT NOT NULL,
  `CAL_A` DECIMAL(19,5) NOT NULL,
  `CAL_B` DECIMAL(19,5) NOT NULL,
  `CAL_A_DIVIDE_CAL_B` DECIMAL(19,5) NOT NULL,
  `CURRENT_MONTH_RESERVE` DECIMAL(19,5) NOT NULL,
  `PRIOR_MONTH_RESERVE` DECIMAL(19,5) NOT NULL,
  `MOVEMENT` DECIMAL(19,5) NOT NULL,
  `ABSOLUTE_MOVEMENT` DECIMAL(19,5) NOT NULL,
  `CURRENT_MONTH_RESERVE_PERCENT` DECIMAL(19,5) NOT NULL,
  `PRIOR_MONTH_RESERVE_PERCENT` DECIMAL(19,5) NOT NULL,
  `TEAM_ID` INT NOT NULL,
  `IS_CHECKED` TINYINT(1) NOT NULL DEFAULT 0,
  `JUSTIFICATION` VARCHAR(2000) NOT NULL,
  `LUMP_SUM_VALUE` DECIMAL(19,5) NOT NULL,
  `DAILY_UNWIND_AMOUNT_GBP` DECIMAL(19,5) NOT NULL,
  `TOTAL_UNWIND_AMOUNT_GBP` DECIMAL(19,5) NOT NULL,
  `TOTAL_PREPAYMENT_GBP` DECIMAL(19,5) NOT NULL,
  `TOTAL_INCOME_STATEMENT_GBP` DECIMAL(19,5) NOT NULL,
  `SHORT_TERM_PREPAYMENT_GBP` DECIMAL(19,5) NOT NULL,
  `LONG_TERM_PREPAYMENT_GBP` DECIMAL(19,5) NOT NULL,
  `INCOME_STATEMENT_ACCOUNT` VARCHAR(255) NOT NULL,
  `INCOME_STATEMENT_COST_CENTER` VARCHAR(255) NOT NULL,
  `BALANCE_SHEET_ACCOUNT` VARCHAR(255) NOT NULL,
  `BALANCE_SHEET_COST_CENTER` VARCHAR(255) NOT NULL,
  `VENDOR_BALANCE` DECIMAL(19,5) NOT NULL,
  `RESERVE_STOP_TYPE_ID` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RESERVE_RISK_OPPORTUNITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY_KSB` (
  `RESERVE_RISK_OPPORTUNITY_KSB_ID` INT NOT NULL,
  `RESERVE_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `KSB_ID` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RESERVE_RISK_OPPORTUNITY_KSB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY_MEMO` (
  `RESERVE_RISK_OPPORTUNITY_MEMO_ID` INT NOT NULL,
  `RESERVE_ID` INT NOT NULL,
  `RESERVE_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `PARENT_ID` INT NOT NULL,
  `RESERVE_RISK_OPPORTUNITY_MEMO_STATUS_ID` INT NOT NULL,
  `MONTH` INT NOT NULL,
  `FISCAL_YEAR_ID` INT NOT NULL,
  `RESERVE_VALUE_GBP` DECIMAL(19,5) NOT NULL,
  `LOCAL_CURRENCY` VARCHAR(2000) NOT NULL,
  `LOCAL_CURRENCY_VALUE` DECIMAL(19,5) NOT NULL,
  `DESCRIPTION` VARCHAR(2000) NOT NULL,
  `MEMO_FINANCE_STATUS_ID` INT NOT NULL,
  `GFS_COMMENTS` VARCHAR(2000) NOT NULL,
  `TEAM_ID` INT NOT NULL,
  `SUPPLIER_CLAIM_TYPE_ID` INT NOT NULL,
  `VENDOR_ID` INT NOT NULL,
  `TRANSACTION_TYPE_ID` INT NOT NULL,
  `TRANSACTION_TYPE_BREAKDOWN_ID` INT NOT NULL,
  `EFFECTIVE_DATE` DATE NOT NULL,
  `TRANSACTION_START_DATE` DATE NOT NULL,
  `TRANSACTION_END_DATE` DATE NOT NULL,
  `NON_STANDARD_ACCOUNTING_ID` INT NOT NULL,
  `MYA_REFERENCE` VARCHAR(255) NOT NULL,
  `SCPA_REFERENCE` VARCHAR(255) NOT NULL,
  `LEVER_ID` INT NOT NULL,
  `IMPLEMENTAION_DATE` DATE NOT NULL,
  `SYSTEM_ID` INT NOT NULL,
  `ASSOCIATED_STRATEGIC_BUYER` VARCHAR(255) NOT NULL,
  `GLOBAL_COMMODITY_LEAD_AREA_ID` INT NOT NULL,
  `VENDOR_EXCHANGE_RATE` DECIMAL(19,5) NOT NULL,
  `IS_SYSTEM_GENERATED` TINYINT(1) NOT NULL DEFAULT 0,
  `PREVIOUS_RESERVE_RISK_OPPORTUNITY_MEMO_ID` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RESERVE_RISK_OPPORTUNITY_MEMO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY` (
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `REFERENCE_NUMBER` VARCHAR(255) NOT NULL,
  `NAF_NUMBER` VARCHAR(15) NOT NULL,
  `FIND_ID` INT NOT NULL,
  `WORKFLOW_STATUS_ID` INT NOT NULL,
  `CBSL_STATUS_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_PARENT_ID` INT NOT NULL,
  `VENDOR_ID` INT NOT NULL,
  `DT2_VENDOR_ID` INT NOT NULL,
  `NEW_VENDOR_ID` INT NOT NULL,
  `BUYER_CODE_ID` INT NOT NULL,
  `SUPPLIER_CLAIM_TYPE_ID` INT NOT NULL,
  `FISCAL_YEAR_ID` INT NOT NULL,
  `NOTIFICATION_METHOD_ID` INT NOT NULL,
  `NOTIFICATION_METHOD_JUSTIFICATION` VARCHAR(255) NOT NULL,
  `CONFIDENTIAL` TINYINT(1) NOT NULL DEFAULT 0,
  `TRANSACTION_TYPE_ID` INT NOT NULL,
  `TRANSACTION_TYPE_BREAKDOWN_ID` INT NOT NULL,
  `EFFECTIVE_DATE` DATE NOT NULL,
  `TRANSACTION_START_DATE` DATE NOT NULL,
  `TRANSACTION_END_DATE` DATE NOT NULL,
  `BUDGET_EXCHANGE_RATE` DECIMAL(19,5) NOT NULL,
  `DUMMY_FLAG` TINYINT(1) NOT NULL DEFAULT 0,
  `MYA_REFERENCE` VARCHAR(255) NOT NULL,
  `SCPA_REFERENCE` VARCHAR(255) NOT NULL,
  `LEVER_ID` INT NOT NULL,
  `PAYMENT_RELEASE_DATE` DATE NOT NULL,
  `IMPLEMENTAION_DATE` DATE NOT NULL,
  `DESCRIPTION` VARCHAR(2000) NOT NULL,
  `SYSTEM_ID` INT NOT NULL,
  `NAF_REFERENCE` VARCHAR(255) NOT NULL,
  `ASSOCIATED_STRATEGIC_BUYER` VARCHAR(255) NOT NULL,
  `GLOBAL_COMMODITY_LEAD_AREA_ID` INT NOT NULL,
  `MILESTONE_ID` INT NOT NULL,
  `ANNUAL_FORECAST_LOCAL` DECIMAL(19,5) NOT NULL,
  `LIKELIHOOD_ID` INT NOT NULL,
  `IS_CALCULATE_USING_PART_DATA` TINYINT(1) NOT NULL,
  `JUSTIFICATION` VARCHAR(255) NOT NULL,
  `CALENDARISED_FORECAST_LOCAL` DECIMAL(19,5) NOT NULL,
  `MATERIAL_GROUP_ID` INT NOT NULL,
  `VEHICLE_LINE_ID` INT NOT NULL,
  `IS_MANUAL_INVOICE_REQUIRED` TINYINT(1) NOT NULL DEFAULT 0,
  `MANUAL_INVOICE_NUMBER` VARCHAR(255) NOT NULL,
  `IS_LUMP_SUM_OVERRIDE` TINYINT(1) NOT NULL,
  `PURCHASING_ORGANIZATION` VARCHAR(255) NOT NULL,
  `PURCHASING_GROUP` VARCHAR(255) NOT NULL,
  `COMPANY_CODE` VARCHAR(255) NOT NULL,
  `PLANT_ID` INT NOT NULL,
  `COST_CENTER_ID` INT NOT NULL,
  `ACCOUNT_CODE_ID` INT NOT NULL,
  `VALUE_LOCAL` DECIMAL(19,5) NOT NULL,
  `VALUE_GBP` DECIMAL(19,5) NOT NULL,
  `SUPPLIER_BALANCE` DECIMAL(19,5) NOT NULL,
  `EXTERNAL_SYSTEM_ID` INT NOT NULL,
  `CLAIM_TITLE` VARCHAR(20) NOT NULL,
  `WIPS_CLAIM_NUMBER` VARCHAR(20) NOT NULL,
  `MANAGER_CODE` VARCHAR(20) NOT NULL,
  `S4_HANA_SUPPLIER_CODE` VARCHAR(50) NOT NULL,
  `PO_NUMBER` VARCHAR(255) NOT NULL,
  `GROSS_CLAIM_LOCAL` DECIMAL(19,5) NOT NULL,
  `PO_DESCRIPTION` VARCHAR(40) NOT NULL,
  `NON_STANDARD_ACCOUNTING_ID` INT NOT NULL,
  `SHIP_FROM_GSDB` VARCHAR(255) NOT NULL,
  `IS_HISTORICAL_PRECEDENCE` TINYINT(1) NOT NULL,
  `IS_VOLUME_ADJUST_RESERVE` TINYINT(1) NOT NULL,
  `IS_ALL_DATES_VALIDATED` TINYINT(1) NOT NULL,
  `IS_UNUSUAL_ACCOUNTING_TREATMENT` TINYINT(1) NOT NULL,
  `COMMENTRY` VARCHAR(255) NOT NULL,
  `REPORTING_CATEGORY_ID` INT NOT NULL,
  `FINANACE_COMMENTS` VARCHAR(4000) NOT NULL,
  `CALENDARIZED_BUYER_PERFORMANCE` DECIMAL(19,5) NOT NULL,
  `COMMODITY` VARCHAR(255) NOT NULL,
  `INDEX_SOURCE` VARCHAR(255) NOT NULL,
  `INITIAL_RATE` DECIMAL(19,5) NOT NULL,
  `PRICE_UPDATE_INTERVAL_ID` INT NOT NULL,
  `AMM_REASON` VARCHAR(255) NOT NULL,
  `APPROVAL_DATE` DATE NOT NULL,
  `IS_MANUAL_RPA_PROCESSING` TINYINT(1) NOT NULL DEFAULT 0,
  `WIPS_PM_CODE` VARCHAR(10) NOT NULL,
  `WIPS_RPA_ERROR` VARCHAR(4000) NOT NULL,
  `IMPLEMENTED_DATE` DATE NOT NULL,
  `IS_MONTHLY_FLAG` TINYINT(1) NOT NULL DEFAULT 0,
  `RESERVE_STOP_TYPE_ID` INT NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RISK_OPPORTUNITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_CO2` (
  `RISK_OPPPRTUNITY_CO2_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `CO2E_START_POSITION` DECIMAL(19,5) NOT NULL,
  `CO2E_END_POSITION` DECIMAL(19,5) NOT NULL,
  `CO2E_DELTA_POSITION` DECIMAL(19,5) NOT NULL,
  `CO2E_CHANGE_DATE` DATE NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RISK_OPPPRTUNITY_CO2_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_INFLATION` (
  `INFLATION_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `INFLATION_TYPE_ID` INT NOT NULL,
  `INFLATION_TYPE_OTHER` VARCHAR(255) NOT NULL,
  `ENERGY_MATERIAL_TYPE_ID` INT NOT NULL,
  `ENERGY_MATERIAL_TYPE_OTHER` VARCHAR(255) NOT NULL,
  `UNIT_MEASURE_ID` INT NOT NULL,
  `UNIT_MEASURE_OTHER` VARCHAR(255) NOT NULL,
  `NEW_RATE` DECIMAL(19,5) NOT NULL,
  `BASE_RATE` DECIMAL(19,5) NOT NULL,
  `RATE_DELTA` DECIMAL(19,5) NOT NULL,
  `BASE_POSITION_ID` INT NOT NULL,
  `BASE_POSITION_OTHER` VARCHAR(255) NOT NULL,
  `PAIN_SHARE_PERCENT` DECIMAL(19,5) NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PART` (
  `RISK_OOPORTUNITY_PART_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `PART_ID` INT NOT NULL,
  `PLANT_ID` INT NOT NULL,
  `CURRENT_VALUE` DECIMAL(19,5) NOT NULL,
  `CURRENT_VALUE_CURRENCY` VARCHAR(255) NOT NULL,
  `EFFECTIVE_DATE_FROM` DATE NOT NULL,
  `EFFECTIVE_DATE_TO` DATE NOT NULL,
  `IS_CURRENT_VALUE_CHANGED` TINYINT(1) NOT NULL,
  `CURRENT_VALUE_CHANGE_REASONING` VARCHAR(255) NOT NULL,
  `ABSOLUTE_PART_PRICE_CHANGE` DECIMAL(19,5) NOT NULL,
  `NEW_PART_PRICE` DECIMAL(19,5) NOT NULL,
  `NEW_PART_PRICE_CURRENCY` VARCHAR(255) NOT NULL,
  `PRICE_DIFFERENCE` DECIMAL(19,5) NOT NULL,
  `PERCENT_DIFFERENCE` DECIMAL(19,5) NOT NULL,
  `IS_RUNOUT` TINYINT(1) NOT NULL DEFAULT 0,
  `RUNOUT_DATE` DATE NOT NULL,
  `ATP_REFERENCE` VARCHAR(255) NOT NULL,
  `FTO_VOLUME_CALCULATION` DECIMAL(19,5) NOT NULL,
  `PRIOR_YEAR_CALENDARIZED_VOLUMES` DECIMAL(19,5) NOT NULL,
  `CURRENT_YEAR_CALENDARIZED_VOLUMES` DECIMAL(19,5) NOT NULL,
  `FULL_FISCAL_BUYER_PERFORMANCE_CALCULATION` DECIMAL(19,5) NOT NULL,
  `CALENDARIZED_BUYER_PERFORMANCE_CALCULATION` DECIMAL(19,5) NOT NULL,
  `CURRENT_FULL_YEAR_PART_VOLUMES` DECIMAL(19,5) NOT NULL,
  `PRIOR_YEAR_FINANCIAL_IMPACT_LOCAL` DECIMAL(19,5) NOT NULL,
  `PRIOR_YEAR_FINANCIAL_IMPACT_GBP` DECIMAL(19,5) NOT NULL,
  `CURRENT_YEAR_FINANCIAL_IMPACT_LOCAL` DECIMAL(19,5) NOT NULL,
  `CURRENT_YEAR_FINANCIAL_IMPACT_GBP` DECIMAL(19,5) NOT NULL,
  `REMAINING_FINANCIAL_YEAR_IMPACT` DECIMAL(19,5) NOT NULL,
  `ACTUAL_FINANCIAL_IMPACT` DECIMAL(19,5) NOT NULL,
  `IS_UPLOADED_BY_CBSL` TINYINT(1) NOT NULL DEFAULT 0,
  `CBSL_COMMENTS` VARCHAR(2000) NOT NULL,
  `BUYER_COMMENTS` VARCHAR(2000) NOT NULL,
  `AMM_LINKED_VALUE` DECIMAL(19,5) NOT NULL,
  `AMM_MEASURE_UNIT` VARCHAR(255) NOT NULL,
  `AMM_TOTAL_WEIGHT` DECIMAL(19,5) NOT NULL,
  `AMM_NET_WEIGHT` DECIMAL(19,5) NOT NULL,
  `AMM_GROSS_WEIGHT` DECIMAL(19,5) NOT NULL,
  `IS_EXCLUDED` TINYINT(1) NOT NULL DEFAULT 0,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE NOT NULL,
  `IS_ARCHIVED` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RISK_OOPORTUNITY_PART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ACTIVITY_FIELD_LEVEL_LOG` (
  `ACTIVITY_FIELD_LEVEL_LOG_ID` INT NOT NULL,
  `ACTIVITY_LOG_ID` INT,
  `FIELD_NAME` VARCHAR(255),
  `FIELD_LABEL` VARCHAR(255),
  `OLD_VALUE` VARCHAR(255),
  `NEW_VALUE` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL,
  `ARCHIVAL_DATE` DATE,
  `IS_ARCHIVED` TINYINT(1),
  PRIMARY KEY (`ACTIVITY_FIELD_LEVEL_LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ACTIVITY_FIELD_LEVEL_LOG_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `NEW_VALUE` VARCHAR(255),
  `OLD_VALUE` VARCHAR(255),
  `FIELD_LABEL` VARCHAR(255),
  `FIELD_NAME` VARCHAR(255),
  `ACTIVITY_LOG_ID` INT,
  `ACTIVITY_FIELD_LEVEL_LOG_ID` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ACTIVITY_LOG` (
  `IS_ARCHIVED` TINYINT(1),
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(255),
  `DESCRIPTION` VARCHAR(2000),
  `ACTION` VARCHAR(255),
  `ACTIVITY_LOG_ID` INT NOT NULL,
  PRIMARY KEY (`ACTIVITY_LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ACTIVITY_LOG_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL,
  `UPDATED_ON` DATETIME NOT NULL,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(255),
  `ACTION` VARCHAR(255),
  `ACTIVITY_LOG_ID` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_APPROVAL` (
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_APPROVAL_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_APPROVAL_RULE` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `APPROVAL_LIMIT` DECIMAL(19,5),
  `APPROVAL_RULE_ID` INT NOT NULL,
  `FORUM_ID` INT,
  `PROCUREMENT_TEAM_ID` INT,
  `FINANCE_TEAM_ID` INT,
  `IS_POA_INCREASE` TINYINT(1),
  `IS_LUMP_SUM` TINYINT(1),
  PRIMARY KEY (`APPROVAL_RULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_APPROVAL_RULE_REQUEST_CATEGORY` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `APPROVAL_RULE_REQUEST_CATEGORY_ID` INT NOT NULL,
  `APPROVAL_RULE_ID` INT,
  `REQUEST_CATEGORY_ID` INT,
  PRIMARY KEY (`APPROVAL_RULE_REQUEST_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_CURRENCY_EXCHANGE_RATE` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `CURRENCY_EXCHANGE_RATE_ID` INT NOT NULL,
  `CURRENCY_ID` INT,
  `MONTH` INT,
  `FISCAL_YEAR_ID` INT,
  `M_EXCHANGE_RATE` DECIMAL(19,5),
  `Y_EXCHANGE_RATE` DECIMAL(19,5),
  PRIMARY KEY (`CURRENCY_EXCHANGE_RATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_DOCUMENT` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `DOCUMENT_ID` INT NOT NULL,
  `ENTITY_TYPE_ID` INT,
  `ENTITY_ID` INT,
  `DOCUMENT_TYPE_ID` INT,
  `APPIAN_DOCUMENT_ID` INT,
  `DESCRIPTION` VARCHAR(2000),
  `S3_DOCUMENT_STATUS_ID` TINYINT(1) NOT NULL DEFAULT 0,
  `S3_DOUMNET_NAME` VARCHAR(255),
  `S3_DOCUMENT_PATH` VARCHAR(255),
  `S3_BUCKET_OBJECT_KEY` VARCHAR(255),
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_DOCUMENT_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `DOCUMENT_ID` INT NOT NULL,
  `ENTITY_TYPE_ID` INT,
  `ENTITY_ID` INT,
  `DOCUMENT_TYPE_ID` INT,
  `APPIAN_DOCUMENT_ID` INT,
  `DESCRIPTION` VARCHAR(2000),
  `S3_DOCUMENT_STATUS_ID` TINYINT(1) NOT NULL DEFAULT 0,
  `S3_DOUMNET_NAME` VARCHAR(255),
  `S3_DOCUMENT_PATH` VARCHAR(255),
  `S3_BUCKET_OBJECT_KEY` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_E2SC` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `E2SC_ID` INT NOT NULL,
  `LOCATION_ID` VARCHAR(50),
  `SUPPLIER_ITEM_ID` VARCHAR(50),
  `SUPPLIER_ID` VARCHAR(50),
  `CREATION_DATE` DATE,
  `FORECAST_DATE` DATE,
  `FORECAST_QTY` DECIMAL(19,5),
  `EXTRACT_DATE` DATE NOT NULL,
  PRIMARY KEY (`E2SC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ENQUIRY` (
  `UPDATED_BY` VARCHAR(255),
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `ENQUIRY_ID` INT NOT NULL,
  `REQUEST_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `ENQUIRY_STATUS_ID` INT,
  `WORKFLOW_STATUS_ID` INT,
  `SUMMARY` VARCHAR(4000),
  `RESPONSE` VARCHAR(4000),
  `IS_ACTION` TINYINT(1) NOT NULL DEFAULT 0,
  `IS_SYSTEM` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ENQUIRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_ENQUIRY_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ENQUIRY_ID` INT NOT NULL,
  `REQUEST_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `ENQUIRY_STATUS_ID` INT,
  `WORKFLOW_STATUS_ID` INT,
  `SUMMARY` VARCHAR(4000),
  `RESPONSE` VARCHAR(4000),
  `IS_ACTION` TINYINT(1) NOT NULL DEFAULT 0,
  `IS_SYSTEM` TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_FROZEN_TURNOVER` (
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `FROZEN_TURNOVER_ID` INT NOT NULL,
  `FISCAL_YEAR_ID` INT,
  `CATEGORY` VARCHAR(255),
  `CARLINE` VARCHAR(255),
  `FORD_EMC_TD` VARCHAR(255),
  `ENGINE` VARCHAR(255),
  `FULL_PART_WITH_ONLY_FIRST_LETTER_OF_SUFFIX` VARCHAR(255),
  `FULL_PART` VARCHAR(255),
  `PREFIX` VARCHAR(255),
  `BASE` VARCHAR(255),
  `SUFFIX` VARCHAR(255),
  `PART_DESCRIPTION` VARCHAR(255),
  `T1_SUPPLIER_CODE` VARCHAR(255),
  `T1_SUPPLIER` VARCHAR(255),
  `WIPS_COUNTRY_CODE` VARCHAR(255),
  `T1_PARENT` VARCHAR(255),
  `DT2_SUPPLIER_CODE` VARCHAR(255),
  `DT2_SUPPLIER` VARCHAR(255),
  `DT2_SUPPLIER_COUNTRY_CODE` VARCHAR(255),
  `DT2_PARENT` VARCHAR(255),
  `PIECE_COST_SOURCE_CURRENCY` VARCHAR(255),
  `CURRENCY` VARCHAR(255),
  `EXCHANGE_RATE` VARCHAR(255),
  `PIECE_COST_GBP` VARCHAR(255),
  `SOURCE_TAKE_RATE` VARCHAR(255),
  `TAKE_RATE_AMENDED` VARCHAR(255),
  `CARLINE_VOLUME` VARCHAR(255),
  `ENGINE_PART_VOLUME` VARCHAR(255),
  `ENGINE_TR` VARCHAR(255),
  `PART_VOLUME` VARCHAR(255),
  `VALUE_GBP` VARCHAR(255),
  `VALUE_IN_MILLION` VARCHAR(255),
  PRIMARY KEY (`FROZEN_TURNOVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_GOODS_RECEIPT` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `GOODS_RECEIPT_ID` INT NOT NULL,
  `RESERVE_ID` INT,
  `VENDOR_ID` INT,
  `PART_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `PLANT_ID` INT,
  `DOCUMENT_NO` VARCHAR(255),
  `MOVEMENT_TYPE` VARCHAR(255),
  `PSTNG_DATE` DATE,
  `QUANTITY` DECIMAL(19,5),
  `B_UNIT` VARCHAR(10),
  `ITEM` INT,
  `GOODS_RECEIPT_AGGREGATION_ID` INT,
  PRIMARY KEY (`GOODS_RECEIPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_GOODS_RECEIPT_AGGREGATION` (
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(255),
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `ARCHIVAL_DATE` DATE,
  `GOODS_RECEIPT_AGGREGATION_ID` INT NOT NULL,
  `RESERVE_ID` INT,
  `VENDOR_ID` INT,
  `PART_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `PLANT_ID` INT,
  `QUANTITY` DECIMAL(19,5),
  PRIMARY KEY (`GOODS_RECEIPT_AGGREGATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_GOODS_RECEIPT_AGGREGATION_ARCH` (
  `ARCHIVAL_DATE` DATE,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `GOODS_RECEIPT_AGGREGATION_ID` INT NOT NULL,
  `RESERVE_ID` INT,
  `VENDOR_ID` INT,
  `PART_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `PLANT_ID` INT,
  `QUANTITY` DECIMAL(19,5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_ACCOUNT_CODE` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ACCOUNT_CODE_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  PRIMARY KEY (`ACCOUNT_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_ACTIVITY_TYPE` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ACTIVITY_TYPE_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  PRIMARY KEY (`ACTIVITY_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_APPROVAL_RULE_TEAM` (
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `APPROVAL_RULE_TEAM_ID` INT NOT NULL,
  `IS_PROCUREMENT` TINYINT(1),
  `ORGANIZATION_LEVEL` VARCHAR(255),
  `APPIAN_GROUP_NAME` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_APPROVAL_STATUS` (
  `APPROVAL_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`APPROVAL_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_AUTO_PAM_MONTH` (
  `AUTO_PAM_MONTH_ID` INT NOT NULL,
  `P0_MINUS_MONTH` INT,
  `P0_MONTH` INT,
  `P1_MONTH` INT,
  `P2_MONTH` INT,
  `P3_MONTH` INT,
  `P4_MONTH` INT,
  `P5_MONTH` INT,
  `P6_MONTH` INT,
  `P7_MONTH` INT,
  `P8_MONTH` INT,
  `P9_MONTH` INT,
  `P10_MONTH` INT,
  `P11_MONTH` INT,
  `P12_MONTH` INT,
  `P0_MINUS_FISCAL_DIFFERENCE` INT,
  `P0_FISCAL_DIFFERENCE` INT,
  `P1_FISCAL_DIFFERENCE` INT,
  `P2_FISCAL_DIFFERENCE` INT,
  `P3_FISCAL_DIFFERENCE` INT,
  `P4_FISCAL_DIFFERENCE` INT,
  `P5_FISCAL_DIFFERENCE` INT,
  `P6_FISCAL_DIFFERENCE` INT,
  `P7_FISCAL_DIFFERENCE` INT,
  `P8_FISCAL_DIFFERENCE` INT,
  `P9_FISCAL_DIFFERENCE` INT,
  `P10_FISCAL_DIFFERENCE` INT,
  `P11_FISCAL_DIFFERENCE` INT,
  `P12_FISCAL_DIFFERENCE` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`AUTO_PAM_MONTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_AUTO_PAM_RULE` (
  `AUTO_PAM_RULE_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `DESCRIPTION` VARCHAR(2000),
  `IS_MEMO` TINYINT(1),
  `TRANSACTION_TYPE_ID` INT,
  `IS_DELETED` TINYINT(1),
  `FINANCE_STATUS_ID` INT,
  `IS_IMPLEMENTED_IN_PY` TINYINT(1),
  `IS_IMPLEMENTATION_DATE_ADDED` TINYINT(1),
  `IS_ONE_PART_ADDED` TINYINT(1),
  `MILESTONE_ID` INT,
  `LIKELIHOOD_ID` INT,
  `SUPPLIER_CLAIM_TYPE_ID` INT,
  `REPORTING_CATEGORY_ID` INT,
  `NON_STANDARD_ACCOUNTING_ID` INT,
  `ACTUAL_MONTH_PART_PERCENT` INT,
  `FIRST_FORECAST_MONTH_PART_PERCENT` INT,
  `SUBSEQUENT_MONTHS_PART_PERCENT` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`AUTO_PAM_RULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_CBSL_STATUS` (
  `CBSL_STATUS_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`CBSL_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_COST_CENTER` (
  `COST_CENTER_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`COST_CENTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_COUNTRY` (
  `COUNTRY_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`COUNTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_DOCUMENT_TYPE` (
  `DOCUMENT_TYPE_ID` INT NOT NULL,
  `IS_SYSTEM` TINYINT(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`DOCUMENT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_ENQUIRY_STATUS` (
  `ENQUIRY_STATUS_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`ENQUIRY_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_ENTITY_TYPE` (
  `ENTITY_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`ENTITY_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_EXCLUDE_INCLUDE` (
  `EXCLUDE_INCLUDE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`EXCLUDE_INCLUDE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_EXECUTION_LOG_STATUS` (
  `EXECUTION_LOG_STATUS_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`EXECUTION_LOG_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_EXECUTION_LOG_TYPE` (
  `EXECUTION_LOG_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`EXECUTION_LOG_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_FORUM` (
  `FORUM_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`FORUM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_FUTURE_MONTH` (
  `FUTURE_MONTH_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CURRENT_MONTH_ID` INT,
  `SUBSEQUENT_MONTH_ID` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`FUTURE_MONTH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_LIKELIHOOD` (
  `LIKELIHOOD_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`LIKELIHOOD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_MASTER` (
  `MASTER_ID` INT NOT NULL,
  `TABLE_NAME` VARCHAR(255),
  `TABLE_ID` INT,
  `NAME` VARCHAR(255),
  `DESCRIPTION` VARCHAR(255),
  `IS_ENERGY` TINYINT(1) NOT NULL DEFAULT 0,
  `FK_ID1` INT,
  `FK_ID2` INT,
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`MASTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_MATERIAL_GROUP` (
  `MATERIAL_GROUP_ID` INT NOT NULL,
  `IS_PAYABLE` TINYINT(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `DESCRIPTION` VARCHAR(255),
  `ACCOUNT_CODE_ID` INT,
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`MATERIAL_GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_MILESTONE` (
  `MILESTONE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`MILESTONE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_NOTIFICATION_METHOD` (
  `NOTIFICATION_METHOD_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`NOTIFICATION_METHOD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PART_ARCH` (
  `PART_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VENDOR_ID` INT,
  `MATERIAL` VARCHAR(255),
  `PREFIX` VARCHAR(50),
  `BASE` VARCHAR(50),
  `SUFFIX` VARCHAR(50),
  `PART_NUMBER` VARCHAR(255),
  `PART_DESCRIPTION` VARCHAR(255),
  `WHITE_COLOURED_PREFIX` VARCHAR(50),
  `WHITE_COLOURED_BASE` VARCHAR(50),
  `WHITE_COLOURED_SUFFIX` VARCHAR(50),
  `WHITE_COLOURED_PART_NUMBER` VARCHAR(255),
  `COLOURED_PART_INDICATOR` TINYINT(1),
  `MRP_VIEW_MAINTAINED` TINYINT(1),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`PART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PART_PRICE` (
  `PART_PRICE_ID` INT NOT NULL,
  `IS_IN_USE` TINYINT(1) DEFAULT 0,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PART_ID` INT,
  `CURRENT_VALUE` DECIMAL(19,5),
  `CURRENT_VALUE_CURRENCY` VARCHAR(255),
  `EFFECTIVE_DATE_FROM` DATE,
  `EFFECTIVE_DATE_TO` DATE,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`PART_PRICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PART_PRICE_ARCH` (
  `PART_PRICE_ID` INT NOT NULL,
  `IS_IN_USE` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PART_ID` INT,
  `CURRENT_VALUE` DECIMAL(19,5),
  `CURRENT_VALUE_CURRENCY` VARCHAR(255),
  `EFFECTIVE_DATE_FROM` DATE,
  `EFFECTIVE_DATE_TO` DATE,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`PART_PRICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PHASE` (
  `PHASE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`PHASE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_PRICE_UPDATE_INTERVAL` (
  `PRICE_UPDATE_INTERVAL_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`PRICE_UPDATE_INTERVAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_REPORTING_CATEGORY` (
  `REPORTING_CATEGORY_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `REASON_CODE` VARCHAR(50),
  `EXCLUDE_INCLUDE_ID` INT,
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REPORTING_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_REQUEST_AUDIT_TYPE` (
  `REQUEST_AUDIT_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REQUEST_AUDIT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_REQUEST_CATEGORY` (
  `REQUEST_CATEGORY_ID` INT NOT NULL,
  `IS_AD_HOC` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REQUEST_CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_REQUEST_STATUS` (
  `REQUEST_STATUS_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REQUEST_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_REQUEST_TYPE` (
  `REQUEST_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REQUEST_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RISK_FACTOR` (
  `RISK_FACTOR_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`RISK_FACTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_RPA_ERROR_STATUS` (
  `RPA_ERROR_STATUS_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`RPA_ERROR_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TASK_SLA` (
  `TASK_SLA_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TASK_TYPE_ID` INT,
  `IS_HOURLY` TINYINT(1),
  `SLA` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`TASK_SLA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TASK_STATUS` (
  `TASK_STATUS_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`TASK_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TASK_TYPE` (
  `TASK_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`TASK_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_TD_SUB_TYPE` (
  `TD_SUB_TYPE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`TD_SUB_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_VEHICLE_LINE` (
  `VEHICLE_LINE_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `NAME` VARCHAR(255),
  `PLANT_ID` INT,
  `COST_CENTER_ID` INT,
  `SORT_ORDER` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`VEHICLE_LINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REF_VENDOR_REMIT_PARTNER` (
  `VENDOR_REMIT_PARTNER_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VENDOR_ID` INT,
  `REMIT_PARTNER` VARCHAR(50),
  `PURCHASE_ORGANISATION` VARCHAR(50),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`VENDOR_REMIT_PARTNER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST` (
  `REQUEST_ID` INT NOT NULL,
  `IS_GTC_PROPOSED_CHANGES` TINYINT(1) DEFAULT 0,
  `IS_PROMPT_PAYMENT` TINYINT(1) DEFAULT 0,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_TYPE_ID` INT,
  `REQUEST_STATUS_ID` INT,
  `APPROVAL_STATUS_ID` INT,
  `TD_SUB_TYPE_ID` INT,
  `BACKGROUND` VARCHAR(2000),
  `PROBLEM_STATEMENT` VARCHAR(2000),
  `REQUEST_DETAILS` VARCHAR(2000),
  `REQUEST_VALUE` DECIMAL(19,5),
  `RISKS_TOTAL` DECIMAL(19,5),
  `OPPORTUNITIES_TOTAL` DECIMAL(19,5),
  `APPROVED_REQUEST_VALUE` DECIMAL(19,5),
  `APPROVED_RISKS_TOTAL` DECIMAL(19,5),
  `APPROVED_OPPORTUNITIES_TOTAL` DECIMAL(19,5),
  `DOA_APPROVAL_REQUIRED` TINYINT(1),
  `DOA_APPROVAL_COMMENT` VARCHAR(255),
  `VENDOR_ID` INT,
  `PO_NUMBERS` VARCHAR(1000),
  `REASON_FOR_PROMPT_PAYMENT` VARCHAR(255),
  `VALUE_INCLUDING_VAT_LOCAL` DECIMAL(19,5),
  `VALUE_INCLUDING_VAT_GBP` DECIMAL(19,5),
  `CURRENT_PAYMENT_TERM` INT,
  `REQUESTED_PAYMENT_TERM` INT,
  `LOST_INCOME_PERCENT_VALUE` DECIMAL(19,5),
  `LOST_INCOME_CASHFLOW_EFFECT` DECIMAL(19,5),
  `BUYER_CODE_ID` INT,
  `REQUEST_CATEGORY_ID` INT,
  `REQUEST_AUDIT_TYPE_ID` INT,
  `REDS_SCORE` VARCHAR(255),
  `OTHER_STACKHOLDER` VARCHAR(255),
  `ARIBA_REFERENCE` VARCHAR(255),
  `FORUM_ID` INT,
  `AGENDA_DATETIME` DATETIME,
  `DATE_CLOSED` DATE,
  `PRESENTATOR` VARCHAR(255),
  `MINUTES` VARCHAR(2000),
  `IS_GSPM` TINYINT(1),
  `IS_FBP` TINYINT(1),
  `FBP_COMMENTS` VARCHAR(2000),
  `SIGNED_AGREEMENT_JUSTIFICATION` VARCHAR(255),
  `COMPLETION_DATE` DATE,
  `SHOPPING_CART_NUMBER` VARCHAR(10),
  `ARCHIVAL_DATE` DATE,
  `IS_SIGNED_AGREEMENT` TINYINT(1),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`REQUEST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST_ARCH` (
  `REQUEST_ID` INT NOT NULL,
  `IS_GTC_PROPOSED_CHANGES` TINYINT(1) DEFAULT 0,
  `IS_PROMPT_PAYMENT` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_TYPE_ID` INT,
  `REQUEST_STATUS_ID` INT,
  `APPROVAL_STATUS_ID` INT,
  `TD_SUB_TYPE_ID` INT,
  `BACKGROUND` VARCHAR(2000),
  `PROBLEM_STATEMENT` VARCHAR(2000),
  `REQUEST_DETAILS` VARCHAR(2000),
  `REQUEST_VALUE` DECIMAL(19,5),
  `RISKS_TOTAL` DECIMAL(19,5),
  `OPPORTUNITIES_TOTAL` DECIMAL(19,5),
  `APPROVED_REQUEST_VALUE` DECIMAL(19,5),
  `APPROVED_RISKS_TOTAL` DECIMAL(19,5),
  `APPROVED_OPPORTUNITIES_TOTAL` DECIMAL(19,5),
  `DOA_APPROVAL_REQUIRED` TINYINT(1),
  `DOA_APPROVAL_COMMENT` VARCHAR(255),
  `VENDOR_ID` INT,
  `PO_NUMBERS` VARCHAR(1000),
  `REASON_FOR_PROMPT_PAYMENT` VARCHAR(255),
  `VALUE_INCLUDING_VAT_LOCAL` DECIMAL(19,5),
  `VALUE_INCLUDING_VAT_GBP` DECIMAL(19,5),
  `CURRENT_PAYMENT_TERM` INT,
  `REQUESTED_PAYMENT_TERM` INT,
  `LOST_INCOME_PERCENT_VALUE` DECIMAL(19,5),
  `LOST_INCOME_CASHFLOW_EFFECT` DECIMAL(19,5),
  `BUYER_CODE_ID` INT,
  `REDS_SCORE` VARCHAR(255),
  `REQUEST_CATEGORY_ID` INT,
  `REQUEST_AUDIT_TYPE_ID` INT,
  `OTHER_STACKHOLDER` VARCHAR(255),
  `ARIBA_REFERENCE` VARCHAR(255),
  `FORUM_ID` INT,
  `AGENDA_DATETIME` DATETIME,
  `DATE_CLOSED` DATE,
  `PRESENTATOR` VARCHAR(255),
  `MINUTES` VARCHAR(2000),
  `IS_GSPM` TINYINT(1),
  `IS_FBP` TINYINT(1),
  `FBP_COMMENTS` VARCHAR(2000),
  `IS_SIGNED_AGREEMENT` TINYINT(1),
  `SIGNED_AGREEMENT_JUSTIFICATION` VARCHAR(255),
  `COMPLETION_DATE` DATE,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`REQUEST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST_RISK_FACTOR` (
  `REQUEST_RISK_FACTOR_ID` INT NOT NULL,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_ID` INT,
  `RISK_FACTOR_ID` INT,
  `RISK_FACTOR_OTHER` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`REQUEST_RISK_FACTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST_RISK_FACTOR_ARCH` (
  `REQUEST_RISK_FACTOR_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_ID` INT,
  `RISK_FACTOR_ID` INT,
  `RISK_FACTOR_OTHER` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST_RISK_OPPORTUNITY` (
  `REQUEST_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `REJECTION_COMMENT` VARCHAR(4000),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE,
  PRIMARY KEY (`REQUEST_RISK_OPPORTUNITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_REQUEST_RISK_OPPORTUNITY_ARCH` (
  `REQUEST_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REQUEST_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `REJECTION_COMMENT` VARCHAR(4000),
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_ARCH` (
  `RESERVE_ID` INT NOT NULL,
  `IS_CALCULATIONS_COMPLETE` TINYINT(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MONTH` INT,
  `FISCAL_YEAR_ID` INT,
  `RESERVE_STATUS_ID` INT,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_BY` VARCHAR(255),
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY_ARCH` (
  `RESERVE_RISK_OPPORTUNITY_ID` INT NOT NULL,
  `RESERVE_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `RESERVE_RISK_OPPORTUNITY_STATUS_ID` INT,
  `RESERVE_FINANCE_STATUS_ID` INT,
  `AGEING_ID` INT,
  `CAL_A` DECIMAL(19,5),
  `CAL_B` DECIMAL(19,5),
  `CAL_A_DIVIDE_CAL_B` DECIMAL(19,5),
  `CURRENT_MONTH_RESERVE` DECIMAL(19,5),
  `PRIOR_MONTH_RESERVE` DECIMAL(19,5),
  `MOVEMENT` DECIMAL(19,5),
  `ABSOLUTE_MOVEMENT` DECIMAL(19,5),
  `CURRENT_MONTH_RESERVE_PERCENT` DECIMAL(19,5),
  `PRIOR_MONTH_RESERVE_PERCENT` DECIMAL(19,5),
  `TEAM_ID` INT,
  `IS_CHECKED` TINYINT(1) NOT NULL DEFAULT 0,
  `JUSTIFICATION` VARCHAR(2000),
  `LUMP_SUM_VALUE` DECIMAL(19,5),
  `DAILY_UNWIND_AMOUNT_GBP` DECIMAL(19,5),
  `TOTAL_UNWIND_AMOUNT_GBP` DECIMAL(19,5),
  `TOTAL_PREPAYMENT_GBP` DECIMAL(19,5),
  `TOTAL_INCOME_STATEMENT_GBP` DECIMAL(19,5),
  `SHORT_TERM_PREPAYMENT_GBP` DECIMAL(19,5),
  `LONG_TERM_PREPAYMENT_GBP` DECIMAL(19,5),
  `INCOME_STATEMENT_ACCOUNT` VARCHAR(255),
  `INCOME_STATEMENT_COST_CENTER` VARCHAR(255),
  `BALANCE_SHEET_ACCOUNT` VARCHAR(255),
  `BALANCE_SHEET_COST_CENTER` VARCHAR(255),
  `VENDOR_BALANCE` DECIMAL(19,5),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY_KSB_ARCH` (
  `RESERVE_RISK_OPPORTUNITY_KSB_ID` INT NOT NULL,
  `RESERVE_RISK_OPPORTUNITY_ID` INT,
  `KSB_ID` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RESERVE_RISK_OPPORTUNITY_MEMO_ARCH` (
  `RESERVE_RISK_OPPORTUNITY_MEMO_ID` INT NOT NULL,
  `RESERVE_ID` INT,
  `RESERVE_RISK_OPPORTUNITY_ID` INT,
  `PARENT_ID` INT,
  `RESERVE_RISK_OPPORTUNITY_MEMO_STATUS_ID` INT,
  `MONTH` INT,
  `FISCAL_YEAR_ID` INT,
  `RESERVE_VALUE_GBP` DECIMAL(19,5),
  `LOCAL_CURRENCY` VARCHAR(2000),
  `LOCAL_CURRENCY_VALUE` DECIMAL(19,5),
  `DESCRIPTION` VARCHAR(2000),
  `MEMO_FINANCE_STATUS_ID` INT,
  `GFS_COMMENTS` VARCHAR(2000),
  `TEAM_ID` INT,
  `SUPPLIER_CLAIM_TYPE_ID` INT,
  `VENDOR_ID` INT,
  `TRANSACTION_TYPE_ID` INT,
  `TRANSACTION_TYPE_BREAKDOWN_ID` INT,
  `EFFECTIVE_DATE` DATE,
  `TRANSACTION_START_DATE` DATE,
  `TRANSACTION_END_DATE` DATE,
  `NON_STANDARD_ACCOUNTING_ID` INT,
  `MYA_REFERENCE` VARCHAR(255),
  `SCPA_REFERENCE` VARCHAR(255),
  `LEVER_ID` INT,
  `IMPLEMENTAION_DATE` DATE,
  `SYSTEM_ID` INT,
  `ASSOCIATED_STRATEGIC_BUYER` VARCHAR(255),
  `GLOBAL_COMMODITY_LEAD_AREA_ID` INT,
  `VENDOR_EXCHANGE_RATE` DECIMAL(19,5),
  `IS_SYSTEM_GENERATED` TINYINT(1) DEFAULT 0,
  `PREVIOUS_RESERVE_RISK_OPPORTUNITY_MEMO_ID` INT,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_ARCH` (
  `RISK_OPPORTUNITY_ID` INT NOT NULL,
  `REFERENCE_NUMBER` VARCHAR(255),
  `NAF_NUMBER` VARCHAR(15),
  `FIND_ID` INT,
  `WORKFLOW_STATUS_ID` INT,
  `CBSL_STATUS_ID` INT,
  `RISK_OPPORTUNITY_PARENT_ID` INT,
  `VENDOR_ID` INT,
  `DT2_VENDOR_ID` INT,
  `NEW_VENDOR_ID` INT,
  `BUYER_CODE_ID` INT,
  `SUPPLIER_CLAIM_TYPE_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `NOTIFICATION_METHOD_ID` INT,
  `NOTIFICATION_METHOD_JUSTIFICATION` VARCHAR(255),
  `CONFIDENTIAL` TINYINT(1) DEFAULT 0,
  `TRANSACTION_TYPE_ID` INT,
  `TRANSACTION_TYPE_BREAKDOWN_ID` INT,
  `EFFECTIVE_DATE` DATE,
  `TRANSACTION_START_DATE` DATE,
  `TRANSACTION_END_DATE` DATE,
  `BUDGET_EXCHANGE_RATE` DECIMAL(19,5),
  `DUMMY_FLAG` TINYINT(1) DEFAULT 0,
  `MYA_REFERENCE` VARCHAR(255),
  `SCPA_REFERENCE` VARCHAR(255),
  `LEVER_ID` INT,
  `PAYMENT_RELEASE_DATE` DATE,
  `IMPLEMENTAION_DATE` DATE,
  `DESCRIPTION` VARCHAR(2000),
  `SYSTEM_ID` INT,
  `NAF_REFERENCE` VARCHAR(255),
  `ASSOCIATED_STRATEGIC_BUYER` VARCHAR(255),
  `GLOBAL_COMMODITY_LEAD_AREA_ID` INT,
  `MILESTONE_ID` INT,
  `ANNUAL_FORECAST_LOCAL` DECIMAL(19,5),
  `LIKELIHOOD_ID` INT,
  `IS_CALCULATE_USING_PART_DATA` TINYINT(1),
  `JUSTIFICATION` VARCHAR(255),
  `CALENDARISED_FORECAST_LOCAL` DECIMAL(19,5),
  `MATERIAL_GROUP_ID` INT,
  `VEHICLE_LINE_ID` INT,
  `IS_MANUAL_INVOICE_REQUIRED` TINYINT(1) DEFAULT 0,
  `MANUAL_INVOICE_NUMBER` VARCHAR(255),
  `IS_LUMP_SUM_OVERRIDE` TINYINT(1),
  `PURCHASING_ORGANIZATION` VARCHAR(255),
  `PURCHASING_GROUP` VARCHAR(255),
  `COMPANY_CODE` VARCHAR(255),
  `PLANT_ID` INT,
  `COST_CENTER_ID` INT,
  `ACCOUNT_CODE_ID` INT,
  `EXTERNAL_SYSTEM_ID` INT,
  `CLAIM_NUMBER` VARCHAR(255),
  `VALUE_LOCAL` DECIMAL(19,5),
  `VALUE_GBP` DECIMAL(19,5),
  `SUPPLIER_BALANCE` DECIMAL(19,5),
  `CLAIM_TITLE` VARCHAR(20),
  `WIPS_CLAIM_NUMBER` VARCHAR(20),
  `MANAGER_CODE` VARCHAR(20),
  `S4_HANA_SUPPLIER_CODE` VARCHAR(50),
  `PO_NUMBER` VARCHAR(255),
  `GROSS_CLAIM_LOCAL` DECIMAL(19,5),
  `PO_DESCRIPTION` VARCHAR(40),
  `NON_STANDARD_ACCOUNTING_ID` INT,
  `SHIP_FROM_GSDB` VARCHAR(255),
  `IS_HISTORICAL_PRECEDENCE` TINYINT(1),
  `IS_VOLUME_ADJUST_RESERVE` TINYINT(1),
  `IS_ALL_DATES_VALIDATED` TINYINT(1),
  `IS_UNUSUAL_ACCOUNTING_TREATMENT` TINYINT(1),
  `COMMENTRY` VARCHAR(255),
  `REPORTING_CATEGORY_ID` INT,
  `FINANACE_COMMENTS` VARCHAR(4000),
  `CALENDARIZED_BUYER_PERFORMANCE` DECIMAL(19,5),
  `COMMODITY` VARCHAR(255),
  `INDEX_SOURCE` VARCHAR(255),
  `INITIAL_RATE` DECIMAL(19,5),
  `PRICE_UPDATE_INTERVAL_ID` INT,
  `AMM_REASON` VARCHAR(255),
  `APPROVAL_DATE` DATE,
  `IS_MANUAL_RPA_PROCESSING` TINYINT(1) DEFAULT 0,
  `WIPS_PM_CODE` VARCHAR(10),
  `WIPS_RPA_ERROR` VARCHAR(4000),
  `IMPLEMENTED_DATE` DATE,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_CO2_ARCH` (
  `RISK_OPPPRTUNITY_CO2_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT,
  `CO2E_START_POSITION` DECIMAL(19,5),
  `CO2E_END_POSITION` DECIMAL(19,5),
  `CO2E_DELTA_POSITION` DECIMAL(19,5),
  `CO2E_CHANGE_DATE` DATE,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_INFLATION_ARCH` (
  `INFLATION_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT,
  `INFLATION_TYPE_ID` INT,
  `INFLATION_TYPE_OTHER` VARCHAR(255),
  `ENERGY_MATERIAL_TYPE_ID` INT,
  `ENERGY_MATERIAL_TYPE_OTHER` VARCHAR(255),
  `UNIT_MEASURE_ID` INT,
  `UNIT_MEASURE_OTHER` VARCHAR(255),
  `NEW_RATE` DECIMAL(19,5),
  `BASE_RATE` DECIMAL(19,5),
  `RATE_DELTA` DECIMAL(19,5),
  `BASE_POSITION_ID` INT,
  `BASE_POSITION_OTHER` VARCHAR(255),
  `PAIN_SHARE_PERCENT` DECIMAL(19,5),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PARENT` (
  `RISK_OPPORTUNITY_PARENT_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(4000),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PARENT_ARCH` (
  `RISK_OPPORTUNITY_PARENT_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(4000),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PART_ARCH` (
  `RISK_OOPORTUNITY_PART_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT,
  `PART_ID` INT,
  `PLANT_ID` INT,
  `CURRENT_VALUE` DECIMAL(19,5),
  `CURRENT_VALUE_CURRENCY` VARCHAR(255),
  `EFFECTIVE_DATE_FROM` DATE,
  `EFFECTIVE_DATE_TO` DATE,
  `IS_CURRENT_VALUE_CHANGED` TINYINT(1),
  `CURRENT_VALUE_CHANGE_REASONING` VARCHAR(255),
  `ABSOLUTE_PART_PRICE_CHANGE` DECIMAL(19,5),
  `NEW_PART_PRICE` DECIMAL(19,5),
  `NEW_PART_PRICE_CURRENCY` VARCHAR(255),
  `PRICE_DIFFERENCE` DECIMAL(19,5),
  `PERCENT_DIFFERENCE` DECIMAL(19,5),
  `IS_RUNOUT` TINYINT(1) DEFAULT 0,
  `ATP_REFERENCE` VARCHAR(255),
  `RUNOUT_DATE` DATE,
  `FTO_VOLUME_CALCULATION` DECIMAL(19,5),
  `PRIOR_YEAR_CALENDARIZED_VOLUMES` DECIMAL(19,5),
  `CURRENT_YEAR_CALENDARIZED_VOLUMES` DECIMAL(19,5),
  `FULL_FISCAL_BUYER_PERFORMANCE_CALCULATION` DECIMAL(19,5),
  `CALENDARIZED_BUYER_PERFORMANCE_CALCULATION` DECIMAL(19,5),
  `CURRENT_FULL_YEAR_PART_VOLUMES` DECIMAL(19,5),
  `PRIOR_YEAR_FINANCIAL_IMPACT_LOCAL` DECIMAL(19,5),
  `PRIOR_YEAR_FINANCIAL_IMPACT_GBP` DECIMAL(19,5),
  `CURRENT_YEAR_FINANCIAL_IMPACT_LOCAL` DECIMAL(19,5),
  `CURRENT_YEAR_FINANCIAL_IMPACT_GBP` DECIMAL(19,5),
  `REMAINING_FINANCIAL_YEAR_IMPACT` DECIMAL(19,5),
  `ACTUAL_FINANCIAL_IMPACT` DECIMAL(19,5),
  `IS_UPLOADED_BY_CBSL` TINYINT(1) DEFAULT 0,
  `CBSL_COMMENTS` VARCHAR(2000),
  `BUYER_COMMENTS` VARCHAR(2000),
  `AMM_LINKED_VALUE` DECIMAL(19,5),
  `AMM_MEASURE_UNIT` VARCHAR(255),
  `AMM_TOTAL_WEIGHT` DECIMAL(19,5),
  `AMM_NET_WEIGHT` DECIMAL(19,5),
  `AMM_GROSS_WEIGHT` DECIMAL(19,5),
  `IS_EXCLUDED` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PART_FTO` (
  `RISK_OPPORTUNITY_PART_FTO_ID` INT NOT NULL,
  `RISK_OPORTUNITY_PART_ID` INT,
  `FROZEN_TURNOVER_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `CATEGORY` VARCHAR(255),
  `CARLINE` VARCHAR(255),
  `FORD_EMC_TD` VARCHAR(255),
  `ENGINE` VARCHAR(255),
  `FULL_PART_WITH_ONLY_FIRST_LETTER_OF_SUFFIX` VARCHAR(255),
  `FULL_PART` VARCHAR(255),
  `PREFIX` VARCHAR(255),
  `BASE` VARCHAR(255),
  `SUFFIX` VARCHAR(255),
  `PART_DESCRIPTION` VARCHAR(255),
  `T1_SUPPLIER_CODE` VARCHAR(255),
  `T1_SUPPLIER` VARCHAR(255),
  `WIPS_COUNTRY_CODE` VARCHAR(255),
  `T1_PARENT` VARCHAR(255),
  `DT2_SUPPLIER_CODE` VARCHAR(255),
  `DT2_SUPPLIER` VARCHAR(255),
  `DT2_SUPPLIER_COUNTRY_CODE` VARCHAR(255),
  `DT2_PARENT` VARCHAR(255),
  `PIECE_COST_SOURCE_CURRENCY` VARCHAR(255),
  `CURRENCY` VARCHAR(255),
  `EXCHANGE_RATE` VARCHAR(255),
  `PIECE_COST_GBP` VARCHAR(255),
  `SOURCE_TAKE_RATE` VARCHAR(255),
  `TAKE_RATE_AMENDED` VARCHAR(255),
  `CARLINE_VOLUME` VARCHAR(255),
  `ENGINE_PART_VOLUME` VARCHAR(255),
  `ENGINE_TR` VARCHAR(255),
  `PART_VOLUME` VARCHAR(255),
  `VALUE_GBP` VARCHAR(255),
  `VALUE_IN_MILLION` VARCHAR(255),
  `IS_EDITED` TINYINT(1),
  `COMMENTS` VARCHAR(2000),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`RISK_OPPORTUNITY_PART_FTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PART_FTO_ARCH` (
  `RISK_OPPORTUNITY_PART_FTO_ID` INT NOT NULL,
  `RISK_OPORTUNITY_PART_ID` INT,
  `FROZEN_TURNOVER_ID` INT,
  `FISCAL_YEAR_ID` INT,
  `CATEGORY` VARCHAR(255),
  `CARLINE` VARCHAR(255),
  `FORD_EMC_TD` VARCHAR(255),
  `ENGINE` VARCHAR(255),
  `FULL_PART_WITH_ONLY_FIRST_LETTER_OF_SUFFIX` VARCHAR(255),
  `FULL_PART` VARCHAR(255),
  `PREFIX` VARCHAR(255),
  `BASE` VARCHAR(255),
  `SUFFIX` VARCHAR(255),
  `PART_DESCRIPTION` VARCHAR(255),
  `T1_SUPPLIER_CODE` VARCHAR(255),
  `T1_SUPPLIER` VARCHAR(255),
  `WIPS_COUNTRY_CODE` VARCHAR(255),
  `T1_PARENT` VARCHAR(255),
  `DT2_SUPPLIER_CODE` VARCHAR(255),
  `DT2_SUPPLIER` VARCHAR(255),
  `DT2_SUPPLIER_COUNTRY_CODE` VARCHAR(255),
  `DT2_PARENT` VARCHAR(255),
  `PIECE_COST_SOURCE_CURRENCY` VARCHAR(255),
  `CURRENCY` VARCHAR(255),
  `EXCHANGE_RATE` VARCHAR(255),
  `PIECE_COST_GBP` VARCHAR(255),
  `SOURCE_TAKE_RATE` VARCHAR(255),
  `TAKE_RATE_AMENDED` VARCHAR(255),
  `CARLINE_VOLUME` VARCHAR(255),
  `ENGINE_PART_VOLUME` VARCHAR(255),
  `ENGINE_TR` VARCHAR(255),
  `PART_VOLUME` VARCHAR(255),
  `VALUE_GBP` VARCHAR(255),
  `VALUE_IN_MILLION` VARCHAR(255),
  `IS_EDITED` TINYINT(1),
  `COMMENTS` VARCHAR(2000),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_RISK_OPPORTUNITY_PART_WIPS_CLAIM` (
  `RISK_OPPORTUNITY_PART_WIPS_CLAIM_ID` INT NOT NULL,
  `RISK_OPPORTUNITY_ID` INT,
  `RISK_OOPORTUNITY_PART_ID` INT,
  `RPA_ERROR_STATUS_ID` INT,
  `RPA_ERROR_OTHER` VARCHAR(4000),
  `START_PRICE` DECIMAL(19,5),
  `START_PRICE_CURRENCY` VARCHAR(255),
  `END_PRICE` DECIMAL(19,5),
  `END_PRICE_CURRENCY` VARCHAR(255),
  `MISSING_PART_NUMBER_PREFIX` VARCHAR(255),
  `MISSING_PART_NUMBER_BASE` VARCHAR(255),
  `MISSING_PART_NUMBER_SUFFIX` VARCHAR(255),
  `MISSING_PART_START_PRICE` DECIMAL(19,5),
  `IS_PLANT_SPECIFIC` TINYINT(1) DEFAULT 0,
  `WIPS_PLANT_CODE` VARCHAR(255),
  `WHITE_PART_INDICATOR` TINYINT(1) DEFAULT 0,
  `LINKED_WHITE_PART_NUMBER` VARCHAR(255),
  `WHITE_PART_SUFFIX` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RISK_OPPORTUNITY_PART_WIPS_CLAIM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_SPM_CODE` (
  `SPM_CODE_ID` INT NOT NULL,
  `NAME` VARCHAR(255),
  `APPIAN_USER_ID` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_TASK` (
  `TASK_ID` INT NOT NULL,
  `ENQUIRY_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `TASK_TYPE_ID` INT,
  `TASK_STATUS_ID` INT,
  `ASSIGNED_USER` VARCHAR(255),
  `ASSIGNED_GROUP` VARCHAR(255),
  `COMMENTS` VARCHAR(4000),
  `SLA_DATETIME` DATETIME,
  `COMPLETED_ON` DATETIME,
  `COMPLETED_BY` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE,
  `IS_ARCHIVED` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_TASK_ARCH` (
  `TASK_ID` INT NOT NULL,
  `ENQUIRY_ID` INT,
  `RISK_OPPORTUNITY_ID` INT,
  `TASK_TYPE_ID` INT,
  `TASK_STATUS_ID` INT,
  `ASSIGNED_USER` VARCHAR(255),
  `ASSIGNED_GROUP` VARCHAR(255),
  `COMMENTS` VARCHAR(4000),
  `SLA_DATETIME` DATETIME,
  `COMPLETED_ON` DATETIME,
  `COMPLETED_BY` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  `ARCHIVAL_DATE` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MCI_TEAM_CATEGORY_MAPPING` (
  `TEAM_CATEGORY_MAPPING_ID` INT NOT NULL,
  `TEAM_ID` INT,
  `REPORTING_CATEGORY_ID` INT,
  `LEVER_ID` INT,
  `EXCLUDE_INCLUDE_ID` INT,
  `INCOME_STATEMENT_ACCOUNT` VARCHAR(255),
  `INCOME_STATEMENT_COST_CENTER_GB03_ID` INT,
  `INCOME_STATEMENT_COST_CENTER_GB29_ID` INT,
  `RISK_MATERIAL_GROUP_ID` INT,
  `OPPORTUNITY_MATERIAL_GROUP_ID` INT,
  `IS_PREPAYMENT` TINYINT(1),
  `PROVISION_ACCOUNT` VARCHAR(255),
  `ACCRUAL_ACCOUNT` VARCHAR(255),
  `RECEIVABLE_ACCOUNT` VARCHAR(255),
  `BALANCE_SHEET_COST_CENTER` VARCHAR(255),
  `CREATED_BY` VARCHAR(255),
  `CREATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_ON` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TEAM_CATEGORY_MAPPING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
